### ISSUE TITLE
Where can I find flame_static_embedding.pkl?

### ISSUE THREAD

**Issue by Watterry** [eth-ait/aitviewer#15]
Now I can run the code examples/load_template.py with SMPL-X and MANO pkl data. But When I try to run FLAME data, I can download male, female, netrual from FLAME website, but I just can't find the related pkl data on the web. Here is the error:

No such file or directory: './smplx_models\\flame\\flame_static_embedding.pkl'

So the question is where can I find the releated FLAME file?

**Comment by totomobile43** [comment]
You can find the static and dynamic embedding files here: https://github.com/soubhiksanyal/RingNet/tree/master/flame_model
