### ISSUE TITLE
Do i need to download smplx model?

### ISSUE THREAD

**Issue by MathPoem** [eth-ait/aitviewer#17]
assert osp.exists(smplx_path), 'Path {} does not exist!'.format(
       AssertionError: Path ../data/smplx_models does not exist!

when i run quickstart.py i get this rerror.
I upload (https://smpl.is.tue.mpg.de/index.html) and install(https://github.com/vchoutas/smplx) smpl model but i still get this error
Do i need to download smplx model? and if so, where should it be placed?

**Comment by kaufManu** [comment]
Yes, if you'd like to use SMPL models with the viewer, you should download the respective models. If you just want to see if you can run the viewer, it's better to run an example that does not require SMPL, e.g. [`animation.py`](https://github.com/eth-ait/aitviewer/blob/main/examples/animation.py) (I guess the quickstart.py example has a bit of a misleading name :)).

If you want to use SMPL models, you should do the following (as also mentioned in the [README](https://github.com/eth-ait/aitviewer#configuration)):
 - Download the parametric body models that you want to be able to load (e.g. SMPL, SMPL-H, SMPL-X, STAR, FLAME, MANO). Follow the instructions [here](https://github.com/vchoutas/smplx#loading-smpl-x-smplh-and-smpl) how to do that and how to layout the directory structure of the different models.
 - Let's say you've put the models into a folder `$SMPLX_MODELS` in the previous step, i.e. this folder looks like this:
```
$SMPLX_MODELS
├── smpl
│   ├── SMPL_FEMALE.pkl
│   └── SMPL_MALE.pkl
│   └── SMPL_NEUTRAL.pkl
├── smplh
│   ├── SMPLH_FEMALE.pkl
│   └── SMPLH_MALE.pkl
├── mano
|   ├── MANO_RIGHT.pkl
|   └── MANO_LEFT.pkl
└── smplx
    ├── SMPLX_FEMALE.npz
    ├── SMPLX_FEMALE.pkl
    ├── SMPLX_MALE.npz
    ├── SMPLX_MALE.pkl
    ├── SMPLX_NEUTRAL.npz
    └── SMPLX_NEUTRAL.pkl
```
 - You should now update the `smplx_models` configuration parameter to point to `$SMPLX_MODELS`. The README explains the different options how to do this.

Note that you should not have to install the pypi package `smplx` separately, this is done automatically with the installation of the viewer.

Hope this helps.

**Comment by bryanbocao** [comment]
> Yes, if you'd like to use SMPL models with the viewer, you should download the respective models. If you just want to see if you can run the viewer, it's better to run an example that does not require SMPL, e.g. [`animation.py`](https://github.com/eth-ait/aitviewer/blob/main/examples/animation.py) (I guess the quickstart.py example has a bit of a misleading name :)).
> 
> If you want to use SMPL models, you should do the following (as also mentioned in the [README](https://github.com/eth-ait/aitviewer#configuration)):
> 
> * Download the parametric body models that you want to be able to load (e.g. SMPL, SMPL-H, SMPL-X, STAR, FLAME, MANO). Follow the instructions [here](https://github.com/vchoutas/smplx#loading-smpl-x-smplh-and-smpl) how to do that and how to layout the directory structure of the different models.
> * Let's say you've put the models into a folder `$SMPLX_MODELS` in the previous step, i.e. this folder looks like this:
> 
> ```
> $SMPLX_MODELS
> ├── smpl
> │   ├── SMPL_FEMALE.pkl
> │   └── SMPL_MALE.pkl
> │   └── SMPL_NEUTRAL.pkl
> ├── smplh
> │   ├── SMPLH_FEMALE.pkl
> │   └── SMPLH_MALE.pkl
> ├── mano
> |   ├── MANO_RIGHT.pkl
> |   └── MANO_LEFT.pkl
> └── smplx
>     ├── SMPLX_FEMALE.npz
>     ├── SMPLX_FEMALE.pkl
>     ├── SMPLX_MALE.npz
>     ├── SMPLX_MALE.pkl
>     ├── SMPLX_NEUTRAL.npz
>     └── SMPLX_NEUTRAL.pkl
> ```
> 
> * You should now update the `smplx_models` configuration parameter to point to `$SMPLX_MODELS`. The README explains the different options how to do this.
> 
> Note that you should not have to install the pypi package `smplx` separately, this is done automatically with the installation of the viewer.
> 
> Hope this helps.

By ```you should now update the smplx_models configuration parameter to point to $SMPLX_MODELS```, it means
https://github.com/eth-ait/aitviewer/blob/main/aitviewer/aitvconfig.yaml, right? Sorry, I might have missed it in the README.
