### ISSUE TITLE
TRACE: Projects using the aitviewer

### ISSUE THREAD

**Issue by Arthur151** [eth-ait/aitviewer#30]
Dear Kaufmann, Manuel and Vechev, Velko and Mylonopoulos, Dario,

Thank you all for creating such a useful and fantastic visualization lib. As an old user of AitViewer, I'm really happy to see its new features in streaming, can't wait to try.  I have recommanded AitViewer to many friends. 

During developing our recent work :
TRACE: 5D Temporal Regression of Avatars with Dynamic Cameras in 3D Environments (CVPR2023)
project page: http://www.yusun.work/TRACE/TRACE.html
AitViewer helps a lot, especially in checking the dataset loading. 
If possible, please consider to add TRACE to "Projects using the aitviewer". 

Best regard, 
Yu

**Comment by kaufManu** [comment]
Dear Yu,

Many thanks for your kind words and congratulations on your new paper - very nice work!

We're very happy that you find aitviewer useful and more than gladly add TRACE to the list! If you ever have any feature requests, please don't hesitate to reach out, create PRs, etc.!

All the best
Manuel
