### ISSUE TITLE
AssertionError: Path ../data/smplx_models does not exist!

### ISSUE THREAD

**Issue by huzijun1996** [eth-ait/aitviewer#32]
I have already pip install smplx [all], pip install aitviewer, but both Python 3.8 and Python 3.9 are trying 'Quickstart' from:
https://eth-ait.github.io/aitviewer/#quickstart
reporting an error:
Traceback (most recent call last):
  File "/home/xxx/test/test/ait.py", line 6, in <module>
    v.scene.add(SMPLSequence.t_pose())
  File "/home/xxx/anaconda3/envs/ait/lib/python3.9/site-packages/aitviewer/renderables/smpl.py", line 316, in t_pose
    smpl_layer = SMPLLayer(model_type="smplh", gender="neutral")
  File "/home/xxx/anaconda3/envs/ait/lib/python3.9/site-packages/aitviewer/models/smpl.py", line 63, in __init__
    self.bm = smplx.create(
  File "/home/xxx/anaconda3/envs/ait/lib/python3.9/site-packages/smplx/body_models.py", line 2404, in create
    return SMPLX(model_path, **kwargs)
  File "/home/xxx/anaconda3/envs/ait/lib/python3.9/site-packages/smplx/body_models.py", line 969, in __init__
    assert osp.exists(smplx_path), 'Path {} does not exist!'.format(
AssertionError: Path ../data/smplx_models does not exist!

I also encountered almost the same issue when running the 'load_DIP_IMU. py' file in the examples folder. Is there a way for me to add SMPL and SMPLX .pkl files to the program? Could you give me an example?

**Comment by kaufManu** [comment]
Hi,

In order to visualize SMPL sequences, you need to download the SMPL models. Please refer to the [documentation ](https://eth-ait.github.io/aitviewer/parametric_human_models/supported_models.html#installation) for more instructions and this related [issue](https://github.com/eth-ait/aitviewer/issues/17).

**Comment by huzijun1996** [comment]
Dear Dr. Kaufmann,


Thank you very much for your help. I have successfully resolved this issue. I wish you a wonderful day!



Yours sincerely,
 
 
 Hu Zijun






------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Manuel ***@***.***&gt;; 
发送时间: 2023年6月15日(星期四) 晚上11:06
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [eth-ait/aitviewer] AssertionError: Path ../data/smplx_models does not exist! (Issue #32)





 
Hi,
 
In order to visualize SMPL sequences, you need to download the SMPL models. Please refer to the documentation  for more instructions and this related issue.

**Comment by huzijun1996** [comment]
Thank you very much for your help. I have successfully resolved this issue.
