### ISSUE TITLE
How to disable the adptive ground level?

### ISSUE THREAD

**Issue by kunkun0w0** [eth-ait/aitviewer#48]
Hi! Thanks for developing this amazing visualization tool. 

I met a problem when I tried to add a sphere to the scene. Here is my code:
```
sphere = trimesh.creation.icosphere(subdivisions=3, radius=1.0)
vertices = sphere.vertices
faces = sphere.faces
sphere_Meshes = Meshes(vertices, faces, gui_affine=False, color=(0.5, 0.5, 0.5, 1.0), name="obstacle")
v.scene.add(sphere_Meshes)
```
And here is my result:
![image](https://github.com/eth-ait/aitviewer/assets/56219029/5178c79a-a6ea-43c3-83a3-2186d19bad81)

The center of the sphere is supposed on the origin of the coordinate system. So the ground floor should cut the sphere into halves. However, the aitviewer seems to automatically help me to change the ground level to make sure all the objects are above the surface.

So how can I disable this function?

**Comment by ramenguy99** [comment]
Hi! You can use set the following variable to disable the automatic floor setting:

`viewer.auto_set_floor = False`
