### ISSUE TITLE
Could not load the Qt platform plugin

### ISSUE THREAD

**Issue by bb0928** [eth-ait/aitviewer#69]
when running the demo code, i encountered an error:
qt.qpa.plugin: Could not load the Qt platform plugin "offscreen" in "/home/user/CoppeliaSim_Edu_V4_1_0_Ubuntu20_04" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: eglfs, linuxfb, minimal, minimalegl, offscreen, vnc, webgl, xcb.

what's the reason of this error? thanks

**Comment by yamahiroimportant** [comment]
I have same error

**Comment by bryanbocao** [comment]
Same error here

Tried
```
sudo apt install libxcb-cursor0
pip uninstall opencv-python
pip install opencv-python
pip uninstall PyQt5
pip install PyQt5
export QT_DEBUG_PLUGINS=1
```
but did not work for me.
System:
```
Ubuntu 20.04 LTS
```

**Comment by bryanbocao** [comment]
Looks like https://github.com/eth-ait/aitviewer/issues/43#issuecomment-1802564606 
```
pip uninstall opencv-python
pip uninstall opencv-python-headless
pip install opencv-python-headless
```
works for me.

**Comment by bb0928** [comment]
yeah me too. thanks.
